### ISSUE TITLE
Add support for SMC Corvus Eco

### ISSUE THREAD

**Issue by mpdunning** [epics-motor/motorMicos#6]
I've just forked this repo to add support for the Corvus Eco stepper controller, but I thought I'd check first to see if anyone else is working on this.

This stepper-only controller uses the Venus-1 command set, which shares a few commands with the Venus-3 set (which the Hydra uses).

My plan was to use the Hydra driver as a starting point.  This would be my first motor driver, but not my first asyn driver.

[Link to product](https://www.pi-usa.us/en/products/controllers-drivers-motion-control-software/precision-motion-controllers-and-drivers-for-positioning-systems/smc-corvus-eco-smc-series-1204800/)
[Corvus_Venus_eng_2_1.pdf](https://github.com/epics-motor/motorMicos/files/3918261/Corvus_Venus_eng_2_1.pdf)
[Corvus_eco_manual_1_0.pdf](https://github.com/epics-motor/motorMicos/files/3918262/Corvus_eco_manual_1_0.pdf)

**Comment by kmpeters** [comment]
I'm not aware of anyone working on a driver for the Corvus Eco stepper controller.  A search of tech-talk reveals a single email asking if support existed in 2009: https://epics.anl.gov/tech-talk/2009/msg00967.php

**Comment by mpdunning** [comment]
Thanks Kevin.  I started working on this yesterday and found that there is a big oddity with the command set.  There are no per-axis commands to abort, move, get status, and set velocity/acceleration.  
So when an axis is stopped, all axes will be stopped.  
And to move an axis, I have to resort to an ugly workaround:  check the current position of all axes, set the target for the axis I want to move, then set the target to the current position for the axes I don't want to move (so if an axis is moving, it may stop).  
There is also no way to determine if a single axis is moving or not - the status command only reports if ANY axis is moving.

Are these show stoppers for a motor record driver?  Have you ever heard of such a bizarre controller?  It's like they intend it to be used exclusively for coordinated moves (but don't advertise it that way).

Thanks,
Mike

**Comment by MarkRivers** [comment]
The Newport XPS has some of those limitations for motors that are put into a Multiaxis Group.  However, you can still move the individual motors without having to set the target positions of the other axes.  You can only directly query the moving status of the entire group, but there are other ways to figure out when an individual axis is done moving.

You can look at XPSController.cpp and XPSAxis.cpp for some hints.

**Comment by mpdunning** [comment]
Thanks Mark, I'll take a look at XPS.
I've also started a discussion with the vendor to find out if I'm missing something.

**Comment by kmpeters** [comment]
@mpdunning, I've seen some of those limitations with the Newport HXP controller, which is an XPS controller that is running custom firmware.  All of the hexapod's degrees of freedom are in a single multi-axis group, which Mark described above.

The non-standard behavior you describe is not a show-stopper; you can work around some of the quirks of the controller, but it is likely the motor records for the axes will be coupled in ways that make them slightly less user-friendly than truly independent axes.

If the global moving indicator is used to set the done-moving state of all the axes, the user gets a visual indication that the motors behave differently, since moving one puts all the axes in the moving state.

**Comment by mpdunning** [comment]
Mark, Kevin, thanks for your comments.  I submitted a pull request, although I was not able to find workarounds for some of the quirks.  I also discussed this with PI and apparently nobody really knows anything about this controller.
To summarize, the motors behave OK, but due to the command set the driver has the following 'features':
- When any motor is moving, all will report that they are moving.  I could find no way around this.
- Only one motor can be moved at a time.
- Setting velocity and acceleration for any motor sets it for all motors.

Please let me know if you have any suggestions.  I've returned the controller and motors to the user, but might be able to get them back at some point for further development if necessary.

Thanks again.

**Comment by kmpeters** [comment]
Fixed in #7
